### ISSUE TITLE
Failed to parse json data.

### ISSUE THREAD

**Issue by Vishnugadupudi** [nahamsec/crtndstry#7]
Recon/crtndstry$ ./crtndstry.sh snapchat.com
parse error: Invalid numeric literal at line 1, column 15
parse error: Invalid numeric literal at line 1, column 15
parse error: Invalid numeric literal at line 1, column 15
parse error: Invalid numeric literal at line 1, column 15
parse error: Invalid numeric literal at line 1, column 15
parse error: Invalid numeric literal at line 1, column 15
parse error: Invalid numeric literal at line 1, column 15
parse error: Invalid numeric literal at line 1, column 15
parse error: Invalid numeric literal at line 1, column 15

**Comment by Vishnugadupudi** [comment]
https://stackoverflow.com/questions/56136673/parse-error-invalid-numeric-literal-at-line-1-column-6

**Comment by Vishnugadupudi** [comment]
@nahamsec

**Comment by drown95** [comment]
parse error: Invalid numeric literal at line 1, column 15
parse error: Invalid numeric literal at line 1, column 15
parse error: Invalid numeric literal at line 1, column 15
parse error: Invalid numeric literal at line 1, column 15
parse error: Invalid numeric literal at line 1, column 15
parse error: Invalid numeric literal at line 1, column 15
parse error: Invalid numeric literal at line 1, column 15
parse error: Invalid numeric literal at line 1, column 15
parse error: Invalid numeric literal at line 1, column 15

same :(

**Comment by juanCortelezzi** [comment]
I have the same error.
@nahamsec

**Comment by sharmaz11** [comment]
@nahamsec 
Looks like crt.sh issue, not accepting '%'

curl -s https://crt.sh/\?q\=%25api%25.yahoo.com\&output\=json | jq -r '.[].name_value'
parse error: Invalid numeric literal at line 1, column 15

curl -s https://crt.sh/\?q\=%25api%25.yahoo.com\&output\=json
[BEGIN_HEADERS]
Content-Type: application/json
[END_HEADERS]
<BR><BR>Unsupported use of '%'</BODY>
</HTML>

curl -s https://crt.sh/\?q\=%api%.yahoo.com\&output\=json
[BEGIN_HEADERS]
Content-Type: application/json
[END_HEADERS]
<BR><BR>Unsupported use of '%'</BODY>
</HTML>

**Comment by sharmaz11** [comment]
even digicert has issue - getting a 404

curl -s https://ssltools.digicert.com/chainTester/webservice/ctsearch/search?keyword=yahoo.com
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Error: Page Not Found</title>
</head>
<body>
        <P>Error: Page Not Found</P>
</body>
</html>

**Comment by nahamsec** [comment]
In the future please don't just comment to ping me. 

I'm aware of the issue, I'm waiting for crt.sh to finish implementing all their new changes before fixing this :)
